apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-service
  description: A great example Service
  labels:
    system: service
  annotations:
    example.com/service-discovery: artistweb
    circleci.com/project-slug: github/example-org/artist-website
    backstage.io/techdocs-ref: documented-component
  lighthouse:
    baseUrl: https://backstage.mydomain.com/lighthouse-api
  tags:
    - java
    - public
spec:
  type: website
  lifecycle: production
  owner: tallen
